### ISSUE TITLE
Mac ARM64 support?

### ISSUE THREAD

**Issue by barisyild** [openfl/lime#1762] opened 2024-02-21 12:37 UTC
ndll build support for sillicon macs should be added.

**Comment by joshtynjala** [comment] 2024-02-21 15:59
There have been a number of commits in the 8.2.0-Dev branch recently to get Lime ndll builds for Apple Silicon architecture.

**Comment by tobil4sk** [comment] 2024-02-21 16:03
Please see #1640

**Comment by player-03** [comment] 2024-02-21 16:09
Closing as duplicate of 1640.

**Closed as not planned by player-03** 2024-02-21 16:09 UTC
