### ISSUE TITLE
Android Compile Crash On GitHub

### ISSUE THREAD

**Issue by jigsaw-4277821** [openfl/lime#1544] opened 2022-06-10 20:51 UTC
im trying to compile an app and it keeps crashing with this
`/home/runner/haxelib/hxcpp/4,2,1/include/hxcpp.h:23:13: fatal error: 'typeinfo' file not found #include <typeinfo> ^~~~~~~~~~ 1 error generated. Error: Could not create PCH`

**Comment by joshtynjala** [comment] 2022-06-10 20:59
@jigsaw-4277821 Which version of the Android NDK are you using? NDK r21e usually works well. I think that you get this error when you try to use a newer NDK version than that.

**Comment by jigsaw-4277821** [comment] 2022-06-10 21:32
Im using ndk r20b

**Comment by jigsaw-4277821** [comment] 2022-06-10 22:28
@joshtynjala I tryed ndk r21e but nothing changed

**Comment by player-03** [comment] 2022-06-12 17:01
Copying the workflow file from the other issue:

```yml
# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildAndroid:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
          
      - name: Cache haxelib path
        uses: actions/cache@v2
        with:
          path: |
            %~/haxelib%
          key: ${{ runner.os }}-android
          
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.8
        
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: nttld/setup-ndk@v1.0.6
        with:
          ndk-version: r15c

      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install hxcpp > /dev/null
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib install flixel-tools
          haxelib install flixel-ui 
          haxelib install flixel-addons
          haxelib install hscript
          haxelib git linc_luajit https://github.com/jigsaw-4277821/linc_luajit
          haxelib git extension-androidtools https://github.com/jigsaw-4277821/extension-androidtools  
          haxelib git extension-videoview https://github.com/jigsaw-4277821/extension-videoview
          haxelib list
          
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: |
          haxelib run lime setup android
          haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/debug
```

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:02
Anyway, is something wrong?

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:02
With it?

**Comment by player-03** [comment] 2022-06-12 17:02
According to this workflow file, you're using ndk r15c, not r21e. Try changing that.

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:04
Im trying to see if something changes

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:04
Let me one minute to see

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:05
I want to say a little more detail, this wasn't happening 4 day's ago

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:07
@player-03 I changed the sdk to r21e, nothing changed

**Comment by player-03** [comment] 2022-06-12 17:08
I did say that shouldn't matter.

Also, Lime hasn't released an update in the past four days, so not sure about that either.

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:08
Same issue

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:08
What it should have?

**Comment by player-03** [comment] 2022-06-12 17:27
> this wasn't happening 4 day's ago

Another thing to test: go to [the last working attempt](https://github.com/jigsaw-4277821/FNF-PsychEngine-With-Android-Support/actions/runs/2466140150) and click rerun. If that also breaks, no big deal, you're back where we started. But if it still works, then you've learned something important.

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:39
I'll make a backup of it just to be sure

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:43
@player-03 it crashed

**Comment by Motasembltaje** [comment] 2022-06-12 17:51
@jigsaw-4277821 Whats wrong and problem with Psych Engine Saw?

**Comment by jigsaw-4277821** [comment] 2022-06-12 17:56
The hole issue says that, Android Compile Crashes on GitHub

**Comment by player-03** [comment] 2022-06-12 19:58
Nothing in the workflow file should be causing this. None of the haxelibs you downloaded changed. You hard-coded which version of setup-ndk you're using, so that should be fine too. And GitHub cleans up between runs, so nothing outside the workflow file should be capable of causing this.

It's actually kind of amazing that you get the exact same error with the two different NDKs. NDK 21 switched to using clang as the compiler, and in response, hxcpp created an entirely new toolchain file to use. When you test r15c, it's using android-toolchain-gcc.xml, whereas r21e causes it to use android-toolchain-clang.xml. Even though the compiler and toolchain are both different, the error stays the same.

---

~~You could get a bit more information using `lime build android -DHXCPP_VERBOSE`, but they just don't print the information you need. If you wanted, say, the command that produced the error, you'd have to fork hxcpp, add some `Log.info()` statements to `Compiler.precompile()`, rerun tools/hxcpp/compile.hxml, and update your workflow to use the fork.~~

~~I don't know if that's even the correct direction to go in, but since you can't reproduce it on your own machine, your debugging options are really limited.~~

---

Actually forget that for now. There's a much better option. Make a new repo with a simpler project like DisplayingABitmap, and see if GitHub can compile that.

**Comment by jigsaw-4277821** [comment] 2022-06-12 20:57
I'll do that to test

**Comment by jigsaw-4277821** [comment] 2022-06-12 21:06
@player-03 even If I build another app, nothing changed

**Comment by jigsaw-4277821** [comment] 2022-06-12 21:07
Still the same error

**Comment by TerrorGaming473** [comment] 2022-06-12 22:17
pe android end?!!?? 😨

**Comment by player-03** [comment] 2022-06-13 01:54
Which app did you test? I can't find it on your profile. (It doesn't have to be DisplayingABitmap specifically; you could use any simple app that is _not_ based on Flixel.)

**Comment by Aly-Ant0** [comment] 2022-06-13 02:19
> Which app did you test? I can't find it on your profile. (It doesn't have to be DisplayingABitmap specifically; you could use any simple app that is _not_ based on Flixel.)
> 
> Edit: another test worth doing: fork Lime and rerun the latest action. Make sure at least that works.

I'm testing it let me a minute.

**Comment by Aly-Ant0** [comment] 2022-06-13 03:02
![Screenshot_20220613-000156-427](https://user-images.githubusercontent.com/90076069/173272043-8ae858bb-e027-430b-b0b7-8f6e360187c1.png)

**Comment by jigsaw-4277821** [comment] 2022-06-13 03:58
> Which app did you test? I can't find it on your profile. (It doesn't have to be DisplayingABitmap specifically; you could use any simple app that is _not_ based on Flixel.)
> 
> Edit: another test worth doing: fork Lime and rerun the latest action. Make sure at least that works.

I tested and app and I erease the repo

**Comment by player-03** [comment] 2022-06-13 14:57
Did you keep a copy of the workflow file you used? Now that we've confirmed that Lime works but DisplayingABitmap doesn't, we need to figure out what's different.

**Comment by jigsaw-4277821** [comment] 2022-06-13 16:49
Yeap

**Comment by player-03** [comment] 2022-06-13 17:24
...And? Since you didn't post the file, should I assume you have this under control? If so, great. Let us know once you fix it.

**Comment by jigsaw-4277821** [comment] 2022-06-16 20:01
Ok, i just tested, same error

**Comment by player-03** [comment] 2022-06-16 20:02
Link to the results?

**Comment by jigsaw-4277821** [comment] 2022-06-19 15:02
Are the same, no even a change

**Comment by player-03** [comment] 2022-06-19 17:44
Look, if you want this solved, you're going to need to work with me. Evidence points to this _not_ being a problem with Lime, so I'd be within my rights to close this issue and leave you to deal with it on your own. However, I'm willing to continue helping you, just as soon as you do one of two things:

- Follow [steps 1-4 above](#issuecomment-1155495411), and post a link to the result.
- Tell me which of the four steps you're stuck on.

**Comment by jigsaw-4277821** [comment] 2022-06-20 05:07
@player-03 now it got fixed

**Comment by player-03** [comment] 2022-06-20 06:57
Great!

Sometimes, when a bug has no obvious explanation, it fixes itself. You can't rely on that happening, but when it does, by all means take the win.

**Closed by player-03** 2022-06-20 06:57 UTC

**Comment by jigsaw-4277821** [comment] 2022-06-20 20:45
> Great!
> 
> Sometimes, when a bug has no obvious explanation, it fixes itself. You can't rely on that happening, but when it does, by all means take the win.

Yeap
